namespace MenuChanger.Attributes
{
    /// <summary>
    /// Attribute which indicates that a private member should be included in autogenerated menus, such as MenuElementFactory.
    /// </summary>
    public class MenuIncludeAttribute : Attribute
    {
    }
}
