using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MenuChanger.Attributes
{
    /// <summary>
    /// Attribute which indicates that a public member should be ignored in autogenerated menus, such as MenuElementFactory.
    /// </summary>
    public class MenuIgnoreAttribute : Attribute
    {
    }
}
